### ISSUE TITLE
Preload custom wheels in pyodide kernel

### ISSUE THREAD

**Issue by jvailius** [jupyterlite/pyodide-kernel#96] opened 2024-03-07 15:10 UTC
### Problem

I have a custom local wheel that I can make available by moving it into a top level `pypi` folder. Then I can successfully run `%pip install mypkg`. I was wondering if there is a way to pre-load / pre-install custom wheels like it is done with some packages when I open a new notebook. Essentially I'd like to avoid the install step and just do an `import mypkg`.

### Proposed Solution

Not a complete solution but as far as I can see it works this way with the packages included in pyodide. They live in `output_dir/static/pyodide` folder in my build. Maybe custom packages could be included there as well?

I built jupyterlite with `--pyodide https://github.com/pyodide/pyodide/releases/download/0.26.0a3/pyodide-0.26.0a3.tar.bz2`

P.S.: Great and very useful project!

**Comment by bollwyvl** [comment] 2024-03-07 15:28
Closing as a duplicate of #48.

At present, the only semi-automated way to achieve a `%pip`-less install is to "build" a full custom pyodide distribution before running `jupyter lite build`:

- get the full pyodide distribution
- get/build all the dependencies of your wheel(s) _not_ included in the distribution
  - put your wheel these wheels in the pyodide folder
- rebuild the `pyodide-lock.json` file with https://github.com/pyodide/pyodide-lock
- configure `PyodideAdon.pyodide_url` to point at the distribution

Some ways forward:
- #40
- #83

**Closed by bollwyvl** 2024-03-07 15:28 UTC
Labels: enhancement

**Comment by jvailius** [comment] 2024-03-07 15:34
@bollwyvl Thanks for the hints - I'll give it a try. I saw/read the other issue and even tried xeus which indeed solved my initial problem but then left me with other issues like requests that did not work.

**Comment by martinRenou** [comment] 2024-03-07 15:39
> like requests that did not work

I'm curious about this. requests _should work_ with jupyterlite-xeus and xeus-python. If you have an issue with it please open an issue on https://github.com/jupyterlite/xeus so we can discuss it :)

**Comment by jvailius** [comment] 2024-03-07 15:49
> I'm curious about this. requests _should work_ with jupyterlite-xeus and xeus-python.

I tried `fetch` from the js module (seems to make some sense in the browser) which gave me some wasm errors. Then I tried other http libs. I'll add an issue over at xeus.
